component_depth: 5
exclude:
- /node_modules/.*
- /web/.*
languages:
- name: java
  production:
    include:
    - /lambda/src/main/.*\.java
  test:
    exclude:
    - /lambda/src/main/java/model/test/.*\.java
    - /lambda/src/main/java/lambda/test/.*\.java
