component_depth: 5
exclude:
- /node_modules/.*
- /web/.*
languages:
- java
- name: java
  production:
    exclude:
    - /lambda/gradle/*
  test:
    include:
    - /lambda/src/test/.*\.java
    exclude:
    - /lambda/src/main/.*\.java
