component_depth: 6
languages:
- name: java
        production:
                exclude:
                        - /lambda/src/test/.*\.java
        test:
                include:
                        - /lambda/src/test/.*\.java
exclude:
        - /node_modules/.*
        - /web/.*
