component_depth: 5
exclude:
- /node_modules/.*
- /web/.*
languages:
- java
- name: java
  test:
    include:
    - /lambda/src/test/.*\.java
    exclude:
    - /lambda/src/main/java/model/test/.*\.java
    - /lambda/src/main/java/lambda/test/.*\.java
